name: Integation Tests

on:
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  integration:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build Go
      run: make linux

    - name: Build Docker
      uses: docker/build-push-action@v2
      with:
        context: .
        tags: cloudfoundry/bc:latest
        push: false

    - name: Run Tests
      run: |
        docker run -t \
          -e INPUT_FILE=/tmp/simple.tgz \
          -e INPUT_ARGS=--guess \
          -v `pwd`/test_releases:/tmp garethjevans/bc:test
        docker run -t \
          -e INPUT_FILE=/tmp/dependant.tgz \
          -e INPUT_ARGS=--guess \
          -v `pwd`/test_releases:/tmp garethjevans/bc:test
